[package]
name = "jira-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
tempfile = "3.8.0"
ellipse = "0.2.0"
itertools = "0.11.0"

[dev-dependencies]
tempfile = "3.3.0"